urls:
  beaconchain:!!str http://69.50.95.164:3500
  eth: !!str https://eth-holesky.g.alchemy.com/v2/PEJvZ-DdwCRxTp553x-SVJzVodULrs_Q
nstid:
  !!str 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee_0x9d19  