tokens:
- token: ETHUSDT
  sources: chainlink
- token: WSTETHUSDT
  sources: chainlink
- token: NSTETH
  sources: beaconchain
- token: XRPUSDT
  sources: chainlink
- token: BTCUSDT
  sources: chainlink
sender:
  mnemonic: ''
  path: /Users/yc/autotest/localnetV8/node2/config
imua:
  chainid: imuachaintestnet_233-8
  appName: imua
  grpc: 127.0.0.1:10011
  ws: ws://127.0.0.1:19999/websocket
  rpc: http://127.0.0.1:19999
debugger:
  grpc: :40001
status:
  grpc: 50001    
