tokens:
- token: ETHUSDT
  sources: chainlink
- token: WSTETHUSDT
  sources: chainlink
- token: NSTETH
  sources: beaconchain
- token: XRPUSDT
  sources: chainlink
- token: BTCUSDT
  sources: chainlink
sender:
  mnemonic: ''
  path: /workspaces/go-2/localnetV8/node4/config
imua:
  chainid: imuachaintestnet_233-8
  appName: imua
  grpc: 127.0.0.1:10013
  ws: ws://127.0.0.1:19997/websocket
  rpc: http://127.0.0.1:19997
debugger:
  grpc: :40003
status:
  grpc: 50003  